http:
 listener:
  host: "localhost"
  port: "9081"
  path: "/travelOnTip/{serviceType}"
  
  
db:
 oracle:
  host: "localhost"
  port: "1521"
  user: "system"
  password: "oracle"
  instance: "XE"
 